name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.0'
      
      - name: Create .env file
        run: |
          echo APP_REPO=${{ env.APP_REPO }} >> .env
          echo APP_NAME=${{ env.APP_NAME }} >> .env
          # Repita para cada variável necessária

      - name: Run Tests
        run: make test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          tags: |
            ${{ env.APP_REPO }}/${{ env.APP_NAME }}:${{ github.sha }}
            ${{ env.APP_REPO }}/${{ env.APP_NAME }}:latest

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

